version: '3.8'

services:
  stream_wireguard:
    image: linuxserver/wireguard
    container_name: stream_wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - SERVERURL=your-server-domain-or-ip
      - SERVERPORT=51820
      - PEERS=3
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    hostname: 'stream_wireguard'
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
